# Generated by Django 5.2.12 on 2026-03-14 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(db_index=True, max_length=13, unique=True)),
                ('fiel_cer_key', models.CharField(blank=True, help_text='Key en MinIO del .cer', max_length=500)),
                ('fiel_key_key', models.CharField(blank=True, help_text='Key en MinIO del .key', max_length=500)),
                ('fiel_password_encrypted', models.BinaryField(blank=True, help_text='Password encriptada con Fernet', null=True)),
                ('fiel_verificada', models.BooleanField(default=False, help_text='Login probado contra el SAT')),
                ('fiel_verificada_at', models.DateTimeField(blank=True, null=True)),
                ('fiel_expira', models.DateTimeField(blank=True, null=True)),
                ('descarga_activa', models.BooleanField(default=True)),
                ('ultimo_scrape', models.DateTimeField(blank=True, null=True)),
                ('proximo_scrape', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DescargaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('year', models.IntegerField()),
                ('month_start', models.IntegerField()),
                ('month_end', models.IntegerField()),
                ('tipos', models.JSONField(default=list)),
                ('cfdis_descargados', models.IntegerField(default=0)),
                ('cfdis_nuevos', models.IntegerField(default=0)),
                ('cfdis_duplicados', models.IntegerField(default=0)),
                ('errores', models.JSONField(default=list)),
                ('progreso', models.TextField(blank=True, help_text='Último mensaje de progreso')),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Programado'), ('api', 'API')], default='manual', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Descarga Log',
                'verbose_name_plural': 'Descargas Log',
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text="Ej: 'ZeroLatency Prod'", max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('puede_leer', models.BooleanField(default=True)),
                ('puede_trigger_descarga', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresas', models.ManyToManyField(blank=True, help_text='RFCs que puede consultar', to='core.empresa')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='semanal', max_length=20)),
                ('hora_preferida', models.TimeField(help_text='Hora preferida para ejecutar (UTC)')),
                ('dia_semana', models.IntegerField(blank=True, help_text='0=lunes, 6=domingo', null=True)),
                ('jitter_minutos', models.IntegerField(default=30, help_text='Variación aleatoria en minutos')),
                ('max_reintentos', models.IntegerField(default=3)),
                ('meses_atras', models.IntegerField(default=1, help_text='Cuántos meses atrás descargar')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Schedule Config',
                'verbose_name_plural': 'Schedule Configs',
            },
        ),
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('uuid', models.UUIDField(help_text='UUID del Timbre Fiscal Digital', primary_key=True, serialize=False)),
                ('tipo_relacion', models.CharField(choices=[('recibido', 'Recibido'), ('emitido', 'Emitido')], db_index=True, max_length=10)),
                ('version', models.CharField(max_length=5)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('serie', models.CharField(blank=True, max_length=50)),
                ('folio', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(db_index=True, decimal_places=2, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('tipo_comprobante', models.CharField(db_index=True, max_length=5)),
                ('forma_pago', models.CharField(blank=True, max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=10)),
                ('rfc_emisor', models.CharField(db_index=True, max_length=13)),
                ('nombre_emisor', models.CharField(blank=True, max_length=300)),
                ('regimen_fiscal_emisor', models.CharField(blank=True, max_length=10)),
                ('rfc_receptor', models.CharField(db_index=True, max_length=13)),
                ('nombre_receptor', models.CharField(blank=True, max_length=300)),
                ('uso_cfdi', models.CharField(blank=True, max_length=10)),
                ('total_impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('isr_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('xml_minio_key', models.CharField(help_text='Key del XML en MinIO', max_length=500)),
                ('xml_size_bytes', models.IntegerField(default=0)),
                ('estado_sat', models.CharField(choices=[('vigente', 'Vigente'), ('cancelado', 'Cancelado')], db_index=True, default='vigente', max_length=20)),
                ('descargado_at', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(default='rpa', help_text='rpa o manual', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdis', to='core.empresa')),
            ],
            options={
                'verbose_name': 'CFDI',
                'verbose_name_plural': 'CFDIs',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'fecha'], name='core_cfdi_empresa_a5318e_idx'), models.Index(fields=['empresa', 'tipo_relacion', 'fecha'], name='core_cfdi_empresa_cb9166_idx'), models.Index(fields=['rfc_emisor', 'fecha'], name='core_cfdi_rfc_emi_8c7ac0_idx'), models.Index(fields=['rfc_receptor', 'fecha'], name='core_cfdi_rfc_rec_49ce1d_idx')],
            },
        ),
    ]
