# Generated by Django 5.2.12 on 2026-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_minio_key',
            field=models.CharField(blank=True, help_text='Key en MinIO del logo de la empresa', max_length=500),
        ),
    ]
