# Generated by Django 5.2.12 on 2026-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_logo_minio_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('formato', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversion Lead',
                'verbose_name_plural': 'Conversion Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
