# Generated by Django 5.2.12 on 2026-03-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversionlead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionlead',
            options={'ordering': ['-ultima_conversion'], 'verbose_name': 'Conversion Lead', 'verbose_name_plural': 'Conversion Leads'},
        ),
        migrations.RenameField(
            model_name='conversionlead',
            old_name='created_at',
            new_name='primera_conversion',
        ),
        migrations.RemoveField(
            model_name='conversionlead',
            name='formato',
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='conversiones',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='total_excels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='total_pdfs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='ultima_conversion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversionlead',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conversionlead',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=10)),
                ('uuid_cfdi', models.CharField(blank=True, max_length=50)),
                ('rfc_emisor', models.CharField(blank=True, max_length=13)),
                ('rfc_receptor', models.CharField(blank=True, max_length=13)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('archivo_size', models.IntegerField(default=0)),
                ('enviado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.conversionlead')),
            ],
            options={
                'verbose_name': 'Conversion Log',
                'verbose_name_plural': 'Conversion Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
