# Generated by Django 5.2.12 on 2026-03-16 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conversionlead_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdi',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que subió manualmente este CFDI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cfdi',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfdis', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cfdi',
            name='fuente',
            field=models.CharField(choices=[('rpa', 'RPA'), ('manual', 'Manual'), ('upload', 'Upload')], default='rpa', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('email', 'Email'), ('conversion', 'Conversión'), ('download', 'Descarga SAT'), ('fiel', 'FIEL'), ('api', 'API'), ('auth', 'Autenticación'), ('system', 'Sistema'), ('upload', 'Upload XML')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('user_email', models.CharField(blank=True, db_index=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='core_system_level_8bfbf3_idx'), models.Index(fields=['category', 'created_at'], name='core_system_categor_71093b_idx')],
            },
        ),
    ]
