# Generated by Django 5.2.12 on 2026-03-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cfdi_uploaded_by_alter_cfdi_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('fiel_download', 'Descarga FIEL de MinIO'), ('fiel_decrypt', 'Desencriptar FIEL'), ('browser_launch', 'Lanzar navegador'), ('sat_navigate', 'Navegar al portal SAT'), ('sat_login', 'Login en SAT'), ('sat_select_dates', 'Seleccionar fechas'), ('sat_search', 'Búsqueda de CFDIs'), ('sat_download_wait', 'Espera de descarga SAT'), ('sat_download_file', 'Descarga archivo ZIP/XML'), ('engine_run', 'Motor RPA completo'), ('xml_parse', 'Parseo de XMLs'), ('minio_upload', 'Upload a MinIO'), ('db_insert', 'Inserción en PostgreSQL'), ('xml_process', 'Procesar XMLs descargados'), ('browser_close', 'Cerrar navegador'), ('cleanup', 'Limpieza temporal')], max_length=30)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_ms', models.IntegerField(default=0)),
                ('atribuible_a', models.CharField(choices=[('cirrus', 'Nuestro servidor'), ('sat', 'Portal del SAT'), ('red', 'Red/conexión'), ('minio', 'MinIO storage')], default='cirrus', max_length=20)),
                ('exitoso', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('descarga_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetria', to='core.descargalog')),
            ],
            options={
                'verbose_name': 'Descarga Telemetría',
                'verbose_name_plural': 'Descarga Telemetría',
                'ordering': ['inicio'],
            },
        ),
    ]
