# Generated by Django 5.2.12 on 2026-03-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telemetria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdi',
            name='rfc_empresa',
            field=models.CharField(db_index=True, default='', help_text='RFC canónico — define quién tiene acceso (por FIEL verificada)', max_length=13),
        ),
        migrations.AlterField(
            model_name='cfdi',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa que originó la descarga (referencial, NO define acceso)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
