# Generated by Django 5.2.12 on 2026-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rfc_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sync_activa',
            field=models.BooleanField(default=False, help_text='Sincronización automática habilitada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sync_completada',
            field=models.BooleanField(default=False, help_text='Todos los meses descargados'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sync_desde_month',
            field=models.IntegerField(blank=True, help_text='Mes desde el que sincronizar', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sync_desde_year',
            field=models.IntegerField(blank=True, help_text='Año desde el que sincronizar', null=True),
        ),
    ]
