# Generated by Django 5.2.12 on 2026-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_sync_activa_empresa_sync_completada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_empresas', models.IntegerField(default=1)),
                ('max_descargas_mes', models.IntegerField(default=1)),
                ('max_cfdis_visibles', models.IntegerField(default=50)),
                ('max_conversiones_pdf', models.IntegerField(default=10)),
                ('max_conversiones_excel', models.IntegerField(default=3)),
                ('max_uploads_mes', models.IntegerField(default=10)),
                ('api_rest', models.BooleanField(default=False)),
                ('api_nivel', models.CharField(choices=[('none', 'Sin API'), ('read', 'Solo lectura'), ('full', 'Completa')], default='none', max_length=20)),
                ('logo_en_pdf', models.BooleanField(default=False)),
                ('historial_desde_year', models.IntegerField(default=2026)),
                ('historial_desde_month', models.IntegerField(default=1)),
                ('branding_pdf', models.CharField(choices=[('vistoso', 'Cirrus vistoso'), ('discreto', 'Cirrus discreto'), ('logo', 'Logo cliente'), ('white_label', 'Sin marca')], default='vistoso', max_length=20)),
                ('precio_descarga_extra', models.DecimalField(decimal_places=2, default=29, max_digits=10)),
                ('precio_100_cfdis_extra', models.DecimalField(decimal_places=2, default=49, max_digits=10)),
                ('precio_50_pdfs_extra', models.DecimalField(decimal_places=2, default=19, max_digits=10)),
                ('precio_rfc_extra_mes', models.DecimalField(decimal_places=2, default=49, max_digits=10)),
                ('precio_mes_historico', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden'],
            },
        ),
    ]
