# Generated by Django 5.2.12 on 2026-03-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fiel_status',
            field=models.CharField(choices=[('sin_fiel', 'Sin FIEL'), ('verificando', 'Verificando'), ('verificada', 'Verificada'), ('rechazada', 'Rechazada')], default='sin_fiel', help_text='Estado de la verificación FIEL', max_length=20),
        ),
    ]
