# Generated by Django 5.2.12 on 2026-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_solicitudhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=500)),
                ('situacion', models.CharField(blank=True, help_text='Presunto, Definitivo, Desvirtuado, Sentencia Favorable', max_length=100)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_publicacion_dof', models.DateField(blank=True, null=True)),
                ('numero_oficio_presuncion', models.CharField(blank=True, max_length=200)),
                ('fecha_oficio_presuncion', models.DateField(blank=True, null=True)),
                ('numero_oficio_definitivo', models.CharField(blank=True, max_length=200)),
                ('fecha_oficio_definitivo', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Todos los campos originales del CSV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EFOS (69-B)',
                'verbose_name_plural': 'EFOS (69-B)',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['situacion'], name='core_efos_situaci_68772a_idx')],
            },
        ),
    ]
