# Generated by Django 5.2.12 on 2026-03-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan_stripe_price_id_plan_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='actividades_economicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csf_minio_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csf_ultima_descarga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_colonia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_localidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_municipio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_num_ext',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_num_int',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estatus_padron',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_operaciones',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_capital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
