# Generated by Django 5.2.12 on 2026-03-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_csf_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('tipo', models.CharField(choices=[('recibidos', 'Recibidos'), ('emitidos', 'Emitidos')], max_length=15)),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('error', 'Error')], default='en_cola', max_length=15)),
                ('prioridad', models.IntegerField(default=5, help_text='1=máxima (owner/enterprise), 3=alta (pro), 5=media (basico), 9=baja (free)')),
                ('programado_para', models.DateTimeField(help_text='No ejecutar antes de esta fecha/hora')),
                ('cfdis_descargados', models.IntegerField(default=0)),
                ('cfdis_nuevos', models.IntegerField(default=0)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('intentos', models.IntegerField(default=0)),
                ('max_intentos', models.IntegerField(default=5)),
                ('ultimo_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Descarga Job',
                'verbose_name_plural': 'Descarga Jobs',
                'ordering': ['prioridad', 'programado_para'],
                'unique_together': {('empresa', 'year', 'month', 'tipo')},
            },
        ),
    ]
