# Generated by Django 5.2.12 on 2026-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_descarga_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='csd_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csd_cer_key',
            field=models.CharField(blank=True, help_text='MinIO key del .cer del CSD', max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csd_expira',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csd_key_key',
            field=models.CharField(blank=True, help_text='MinIO key del .key del CSD', max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csd_password_encrypted',
            field=models.TextField(blank=True, help_text='Password del CSD encriptado con Fernet'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csd_serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fiel_status',
            field=models.CharField(choices=[('sin_fiel', 'Sin FIEL'), ('verificando', 'Verificando'), ('verificada', 'Verificada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='sin_fiel', help_text='Estado de la verificación FIEL', max_length=20),
        ),
    ]
