# Generated by Django 5.2.12 on 2026-03-21 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_empresa_csd_activo_empresa_csd_cer_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SATHealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True, unique=True)),
                ('total_probes', models.IntegerField(default=0)),
                ('successful_probes', models.IntegerField(default=0)),
                ('failed_probes', models.IntegerField(default=0)),
                ('availability_pct', models.FloatField(default=0)),
                ('avg_total_time_ms', models.IntegerField(blank=True, null=True)),
                ('avg_login_time_ms', models.IntegerField(blank=True, null=True)),
                ('min_total_time_ms', models.IntegerField(blank=True, null=True)),
                ('max_total_time_ms', models.IntegerField(blank=True, null=True)),
                ('most_common_error', models.CharField(blank=True, default='', max_length=20)),
                ('results_by_node', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'SAT Health Summary',
                'verbose_name_plural': 'SAT Health Summaries',
                'ordering': ['-hour'],
            },
        ),
        migrations.CreateModel(
            name='SATHealthProbe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node_id', models.CharField(db_index=True, max_length=20)),
                ('node_ip', models.GenericIPAddressField()),
                ('rfc_used', models.CharField(db_index=True, max_length=13)),
                ('result', models.CharField(choices=[('success', 'Login exitoso'), ('timeout', 'Timeout'), ('login_failed', 'Login fallido'), ('page_error', 'Error cargando página'), ('captcha', 'Captcha detectado'), ('maintenance', 'SAT en mantenimiento'), ('network_error', 'Error de red'), ('browser_error', 'Error de browser'), ('unknown', 'Error desconocido')], db_index=True, max_length=20)),
                ('last_phase_reached', models.CharField(choices=[('dns', 'Resolución DNS'), ('page_load', 'Carga de página'), ('form_visible', 'Formulario visible'), ('fiel_upload', 'Subida de FIEL'), ('login_submit', 'Envío de login'), ('session_active', 'Sesión activa')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('time_dns_ms', models.IntegerField(blank=True, null=True)),
                ('time_page_load_ms', models.IntegerField(blank=True, null=True)),
                ('time_form_visible_ms', models.IntegerField(blank=True, null=True)),
                ('time_fiel_upload_ms', models.IntegerField(blank=True, null=True)),
                ('time_login_submit_ms', models.IntegerField(blank=True, null=True)),
                ('time_session_active_ms', models.IntegerField(blank=True, null=True)),
                ('time_total_ms', models.IntegerField()),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=500)),
                ('sat_url', models.URLField(default='https://portalcfdi.facturaelectronica.sat.gob.mx/')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_probes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'SAT Health Probe',
                'verbose_name_plural': 'SAT Health Probes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'result'], name='core_sathea_timesta_4246b7_idx'), models.Index(fields=['node_id', 'timestamp'], name='core_sathea_node_id_74bf2b_idx'), models.Index(fields=['rfc_used', 'timestamp'], name='core_sathea_rfc_use_00088b_idx')],
            },
        ),
    ]
