# Generated by Django 5.2.12 on 2026-03-22 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sathealthsummary_sathealthprobe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('revocado', 'Revocado')], default='activo', max_length=10)),
                ('puede_ver_cfdis', models.BooleanField(default=True)),
                ('puede_ver_analisis', models.BooleanField(default=True)),
                ('puede_exportar', models.BooleanField(default=True)),
                ('puede_subir_fiel', models.BooleanField(default=False)),
                ('puede_subir_xmls', models.BooleanField(default=False)),
                ('puede_crear_empresa', models.BooleanField(default=False)),
                ('puede_descargar_sat', models.BooleanField(default=False)),
                ('puede_ver_csf', models.BooleanField(default=False)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('cuenta_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_como_colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['-fecha_invitacion'],
                'unique_together': {('cuenta_principal', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ColaboradorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver_cfdis', models.BooleanField(default=True)),
                ('puede_subir_fiel', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asignadas', to='core.colaborador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_con_acceso', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Colaborador de Empresa',
                'verbose_name_plural': 'Colaboradores de Empresas',
                'unique_together': {('colaborador', 'empresa')},
            },
        ),
    ]
