# Generated by Django 5.2.12 on 2026-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_colaborador_colaboradorempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_colaboradores',
            field=models.IntegerField(default=0),
        ),
    ]
