# Generated by Django 5.2.12 on 2026-03-24 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_plan_max_colaboradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_type', models.CharField(choices=[('alta_empresa', 'Alta de Empresa'), ('descarga_cfdis', 'Descarga de CFDIs'), ('csf_mensual', 'CSF Mensual'), ('verificacion_fiel', 'Verificación FIEL')], db_index=True, max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('esperando_sat', 'Esperando SAT'), ('completado', 'Completado'), ('error', 'Error'), ('reintentando', 'Reintentando')], default='pendiente', max_length=20)),
                ('paso_actual', models.IntegerField(default=1)),
                ('total_pasos', models.IntegerField(default=1)),
                ('paso_nombre', models.CharField(default='', max_length=100)),
                ('pasos_detalle', models.JSONField(default=list)),
                ('intento_actual', models.IntegerField(default=1)),
                ('max_intentos', models.IntegerField(default=5)),
                ('proximo_intento', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_por_sat', models.BooleanField(default=False)),
                ('sat_health_al_iniciar', models.FloatField(blank=True, null=True)),
                ('mensaje_cliente', models.CharField(default='Iniciando proceso...', max_length=500)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('errores_acumulados', models.IntegerField(default=0)),
                ('iniciado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Pipeline State',
                'verbose_name_plural': 'Pipeline States',
                'ordering': ['-actualizado'],
                'indexes': [models.Index(fields=['empresa', 'pipeline_type', 'estado'], name='core_pipeli_empresa_bf720e_idx'), models.Index(fields=['estado', 'actualizado'], name='core_pipeli_estado_fd7ad5_idx')],
            },
        ),
    ]
