# Generated by Django 5.2.12 on 2026-03-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pipelinestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargajob',
            name='estado',
            field=models.CharField(choices=[('en_cola', 'En cola'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('completado_vacio', 'Completado sin CFDIs'), ('error', 'Error')], default='en_cola', max_length=20),
        ),
    ]
