# Generated by Django 5.2.12 on 2026-03-31 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_descargajob_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['rfc_empresa', 'fecha'], name='core_cfdi_rfc_emp_f1750b_idx'),
        ),
    ]
