# Generated by Django 5.2.12 on 2026-04-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_idx_cfdi_rfc_empresa_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='chocobo.mxrouting.net', help_text='Servidor SMTP', max_length=200)),
                ('smtp_port', models.IntegerField(default=465, help_text='Puerto SMTP (465=SSL)')),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('smtp_imap_port', models.IntegerField(default=993, help_text='Puerto IMAP (lectura)')),
                ('noreply_email', models.EmailField(default='noreply@nubex.me', help_text='Cuenta para emails automáticos (confirmaciones, alertas, reportes)', max_length=254)),
                ('noreply_password_encrypted', models.BinaryField(blank=True, null=True)),
                ('noreply_display_name', models.CharField(default='Cirrus', max_length=100)),
                ('contacto_email', models.EmailField(default='contactocirrus@nubex.me', help_text='Cuenta para contacto con clientes', max_length=254)),
                ('contacto_password_encrypted', models.BinaryField(blank=True, null=True)),
                ('contacto_display_name', models.CharField(default='Contacto Cirrus', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
