# Generated by Django 5.2.12 on 2026-04-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID del admin principal que recibe alertas', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_bot_token_encrypted',
            field=models.BinaryField(blank=True, help_text='Token del bot de Telegram (encriptado con Fernet)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_bot_username',
            field=models.CharField(blank=True, help_text='Username del bot (ej: Cirrusbot_bot)', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Habilita el envío de alertas vía Telegram'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_send_critical',
            field=models.BooleanField(default=True, help_text="Enviar alertas nivel 'critical' al admin"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_send_error',
            field=models.BooleanField(default=True, help_text="Enviar alertas nivel 'error' al admin"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_send_info',
            field=models.BooleanField(default=False, help_text="Enviar alertas nivel 'info' al admin"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_send_warning',
            field=models.BooleanField(default=True, help_text="Enviar alertas nivel 'warning' al admin"),
        ),
        migrations.CreateModel(
            name='TelegramAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('success', 'Success')], db_index=True, max_length=10)),
                ('category', models.CharField(blank=True, db_index=True, max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('chat_id', models.CharField(help_text='Chat ID destino', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido (deshabilitado)')], db_index=True, max_length=10)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Usuario destinatario si está vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Telegram',
                'verbose_name_plural': 'Alertas Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_telegr_status_5e9113_idx'), models.Index(fields=['level', 'created_at'], name='core_telegr_level_d1cfd0_idx')],
            },
        ),
    ]
