# Generated by Django 5.2.12 on 2026-04-10 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_systemsettings_telegram_admin_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='snowie_agente_id',
            field=models.CharField(blank=True, help_text='agente_id esperado en los webhooks de Snowie (validación)', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='snowie_webhook_secret_encrypted',
            field=models.BinaryField(blank=True, help_text='Secret HMAC compartido con Snowie (Fernet encriptado). Si está vacío, solo se valida agente_id.', null=True),
        ),
        migrations.CreateModel(
            name='SnowieLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('agente_id', models.CharField(db_index=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc_empresa', models.CharField(blank=True, max_length=13, null=True)),
                ('plan_interesado', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('payload_raw', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], db_index=True, default='nuevo', max_length=20)),
                ('notificado_telegram', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Snowie',
                'verbose_name_plural': 'Leads Snowie',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='core_snowie_estado_8782a9_idx'), models.Index(fields=['agente_id', 'creado_en'], name='core_snowie_agente__79c4de_idx')],
            },
        ),
    ]
