# Generated by Django 5.2.12 on 2026-04-19 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_systemsettings_snowie_agente_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdi',
            name='fecha_final_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cfdi',
            name='fecha_inicial_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cfdi',
            name='fecha_pago_nomina',
            field=models.DateField(blank=True, db_index=True, help_text='FechaPago del complemento de nómina — fecha efectiva del pago', null=True),
        ),
        migrations.AddField(
            model_name='cfdi',
            name='tipo_nomina',
            field=models.CharField(blank=True, choices=[('O', 'Ordinaria'), ('E', 'Extraordinaria')], help_text='O=Ordinaria / E=Extraordinaria (aguinaldos, PTU, bonos)', max_length=1),
        ),
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['rfc_empresa', 'fecha_pago_nomina'], name='core_cfdi_rfc_emp_5ff4df_idx'),
        ),
    ]
