# Generated by Django 5.2.12 on 2026-04-19 21:54

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cfdi_fecha_final_pago_cfdi_fecha_inicial_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Asegurar extensión pgvector (idempotente — ya la corrimos manual,
        # pero Django la expone en VectorExtension para futuros entornos).
        VectorExtension(),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ley', 'Ley Federal'), ('reglamento', 'Reglamento'), ('rmf', 'Resolución Miscelánea Fiscal'), ('criterio', 'Criterio Normativo SAT'), ('guia', 'Guía / Instructivo SAT'), ('jurisprudencia', 'Jurisprudencia / Tesis'), ('nif', 'Norma de Información Financiera'), ('catalogo', 'Catálogo SAT'), ('otro', 'Otro documento')], db_index=True, max_length=20)),
                ('fuente_url', models.URLField(blank=True, max_length=500, null=True)),
                ('año_vigencia', models.IntegerField(blank=True, db_index=True, null=True)),
                ('archivo_minio_key', models.CharField(blank=True, max_length=500)),
                ('archivo_tamano_bytes', models.BigIntegerField(default=0)),
                ('archivo_content_type', models.CharField(blank=True, max_length=100)),
                ('hash_sha256', models.CharField(db_index=True, help_text='Hash del archivo para evitar duplicados', max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('indexado', 'Indexado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('chunks_count', models.IntegerField(default=0, help_text='Número de chunks indexados')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('indexado_en', models.DateTimeField(blank=True, null=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ChunkFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('posicion_chunk', models.IntegerField(db_index=True)),
                ('tokens', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.documentofiscal')),
            ],
            options={
                'verbose_name': 'Chunk Fiscal',
                'verbose_name_plural': 'Chunks Fiscales',
                'ordering': ['documento', 'posicion_chunk'],
            },
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['categoria', 'estado'], name='core_docume_categor_95e7da_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['estado', 'creado_en'], name='core_docume_estado_96687f_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkfiscal',
            index=models.Index(fields=['documento', 'posicion_chunk'], name='core_chunkf_documen_75409d_idx'),
        ),
        # Índice HNSW sobre embedding — acelera búsqueda semántica por similitud
        # coseno. Se crea vía SQL raw porque requiere opciones pgvector específicas.
        # m=16 + ef_construction=64 son valores por defecto recomendados.
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS core_chunk_embedding_hnsw_idx "
                "ON core_chunkfiscal USING hnsw (embedding vector_cosine_ops) "
                "WITH (m = 16, ef_construction = 64);"
            ),
            reverse_sql="DROP INDEX IF EXISTS core_chunk_embedding_hnsw_idx;",
        ),
    ]
