# Generated by Django 5.2.12 on 2026-04-19 23:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_documentofiscal_chunkfiscal_and_more'),
    ]

    operations = [
        # Drop índice HNSW antes de alterar la columna — HNSW está ligado
        # a las dimensiones del vector y no soporta alter en caliente.
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS core_chunk_embedding_hnsw_idx;",
            reverse_sql=(
                "CREATE INDEX IF NOT EXISTS core_chunk_embedding_hnsw_idx "
                "ON core_chunkfiscal USING hnsw (embedding vector_cosine_ops) "
                "WITH (m = 16, ef_construction = 64);"
            ),
        ),
        migrations.AlterField(
            model_name='chunkfiscal',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
        # Recrear índice HNSW con las nuevas dimensiones (1024 de bge-m3)
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS core_chunk_embedding_hnsw_idx "
                "ON core_chunkfiscal USING hnsw (embedding vector_cosine_ops) "
                "WITH (m = 16, ef_construction = 64);"
            ),
            reverse_sql="DROP INDEX IF EXISTS core_chunk_embedding_hnsw_idx;",
        ),
    ]
