# Generated by Django 5.2.12 on 2026-04-20 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_apikey_drop_plain_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='core_stripe_estado_e19a05_idx',
            old_name='core_stripe_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='core_stripe_event_t_d56418_idx',
            old_name='core_stripe_type_idx',
        ),
        migrations.RemoveField(
            model_name='documentofiscal',
            name='archivo_minio_key',
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='aplica_a',
            field=models.JSONField(blank=True, default=list, help_text='Lista: persona_fisica, persona_moral, etc.'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='archivo_json_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='archivo_md_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='archivo_original_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='fecha_ultima_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='intentos_conversion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='intentos_embedding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='intentos_validacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='job_id_celery',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='nombre_archivo_original',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='organismo_emisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='temas_clave',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='uuid_archivo',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID usado para el naming de archivos en MinIO', unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='limite_requests_dia',
            field=models.IntegerField(default=1000, help_text='Limit diario según plan (free=0, basico=1000, pro=5000, enterprise=20000)'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ley', 'Ley Federal'), ('reglamento', 'Reglamento'), ('rmf', 'Resolución Miscelánea Fiscal'), ('criterio', 'Criterio Normativo SAT'), ('guia', 'Guía / Instructivo SAT'), ('jurisprudencia', 'Jurisprudencia / Tesis'), ('nif', 'Norma de Información Financiera'), ('catalogo', 'Catálogo SAT'), ('otro', 'Otro documento')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='chunks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('convirtiendo', 'Convirtiendo (Docling)'), ('convertido', 'Convertido a Markdown'), ('validando', 'Validando (Qwen)'), ('rechazado', 'Rechazado — no fiscal'), ('validado', 'Validado — metadata OK'), ('embeddiendo', 'Generando embeddings'), ('indexado', 'Indexado'), ('error', 'Error')], db_index=True, default='recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='hash_sha256',
            field=models.CharField(db_index=True, help_text='Hash del archivo original para evitar duplicados', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
