# Generated by Django 5.2.12 on 2026-05-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_documentofiscal_versionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_solo_stack',
            field=models.BooleanField(default=True, help_text='Si está activo, SOLO se envían al admin alertas de stack (salud SAT, patrones de falla de jobs, servicios caídos, incidentes). Se silencian eventos individuales de descarga, FIEL de clientes y probes individuales.'),
        ),
        migrations.CreateModel(
            name='DescargaIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('timeout', 'Timeout'), ('sat_error', 'Error SAT'), ('fiel_error', 'Error FIEL'), ('gap_detectado', 'Gap detectado'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('resuelto', models.BooleanField(db_index=True, default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='core.empresa')),
                ('job', models.ForeignKey(blank=True, help_text='Job que originó el incidente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='core.descargajob')),
            ],
            options={
                'verbose_name': 'Incidente de Descarga',
                'verbose_name_plural': 'Incidentes de Descarga',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['resuelto', 'creado_en'], name='core_descar_resuelt_74d811_idx'), models.Index(fields=['tipo', 'creado_en'], name='core_descar_tipo_d6dbee_idx')],
            },
        ),
    ]
