# Generated by Django 5.2.12 on 2026-06-16 17:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_systemsettings_telegram_solo_stack_descargaincidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDoctoRelacionado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pago_index', models.PositiveSmallIntegerField(help_text='Indice 1-based del <pago20:Pago> dentro del REP')),
                ('docto_index', models.PositiveSmallIntegerField(help_text='Indice 1-based del <pago20:DoctoRelacionado> dentro del Pago')),
                ('pago_fecha', models.DateTimeField(help_text='@FechaPago')),
                ('pago_forma', models.CharField(blank=True, help_text='@FormaDePagoP', max_length=10)),
                ('pago_moneda', models.CharField(default='MXN', help_text='@MonedaP', max_length=10)),
                ('pago_tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('pago_monto', models.DecimalField(decimal_places=2, help_text='@Monto del Pago completo', max_digits=18)),
                ('pago_num_operacion', models.CharField(blank=True, help_text='@NumOperacion (referencia bancaria, # cheque, etc.)', max_length=100)),
                ('id_documento', models.CharField(db_index=True, help_text='UUID de la factura PPD pagada (@IdDocumento) — clave del cruce PPD<->REP', max_length=36)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('serie', models.CharField(blank=True, max_length=25)),
                ('moneda_dr', models.CharField(default='MXN', max_length=10)),
                ('equivalencia_dr', models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=14)),
                ('num_parcialidad', models.PositiveSmallIntegerField()),
                ('imp_saldo_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('imp_pagado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('imp_saldo_insoluto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('objeto_imp_dr', models.CharField(blank=True, help_text='01=no objeto / 02=si objeto IVA / 03=no obligado a desglosar', max_length=10)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('factura_cfdi', models.ForeignKey(blank=True, db_column='factura_cfdi_uuid', help_text="CFDI tipo='I' (factura PPD) que este DoctoRelacionado paga, si esta en BD", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reps_recibidos', to='core.cfdi')),
                ('rep_cfdi', models.ForeignKey(db_column='rep_cfdi_uuid', help_text="CFDI tipo='P' que contiene el complemento pago20", on_delete=django.db.models.deletion.CASCADE, related_name='doctos_relacionados', to='core.cfdi')),
            ],
            options={
                'verbose_name': 'DoctoRelacionado de REP (pago20)',
                'verbose_name_plural': 'DoctosRelacionados de REPs',
                'indexes': [models.Index(fields=['id_documento'], name='pdr_id_doc_idx'), models.Index(fields=['factura_cfdi'], name='pdr_factura_idx')],
                'unique_together': {('rep_cfdi', 'pago_index', 'docto_index')},
            },
        ),
    ]
