# Generated by Django 5.2.12 on 2026-06-16 23:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_pagodoctorelacionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('cfdi', models.OneToOneField(db_column='cfdi_uuid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nomina_detalle', serialize=False, to='core.cfdi')),
                ('version', models.CharField(default='1.2', max_length=10)),
                ('num_dias_pagados', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_otros_pagos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_sueldos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_exento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_separacion_indemnizacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_jubilacion_pension', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_impuestos_retenidos_nomina', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_otras_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('subsidio_causado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tipo_regimen', models.CharField(blank=True, help_text='02=Sueldos / 09=Asimilados / 13=Indemnizaciones / ... (catalogo SAT)', max_length=10)),
                ('periodicidad_pago', models.CharField(blank=True, help_text='01=Diario / 02=Semanal / 04=Quincenal / 05=Mensual / ... (catalogo SAT)', max_length=10)),
                ('registro_patronal', models.CharField(blank=True, help_text='Registro IMSS del patron (@nomina12:Emisor/@RegistroPatronal)', max_length=30)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de Nomina (complemento)',
                'verbose_name_plural': 'Detalles de Nomina',
            },
        ),
    ]
