# Generated by Django 5.2.12 on 2026-06-17 01:04
#
# Bloque C: agrega columna regimen_fiscal_receptor a core_cfdi
# + crea tabla core_cfdirelacionadolink.
#
# Guarda de seguridad: SET lock_timeout='5s' antes del ALTER TABLE para
# que aborte limpio si no consigue ACCESS EXCLUSIVE sobre core_cfdi
# en 5 segundos (en lugar de trabar cirrus-web indefinidamente).
# En PG 16 + DEFAULT '' constante el ADD COLUMN es metadata-only y
# normalmente tarda <100 ms, asi que 5s es holgura suficiente.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Esta migracion contiene RunSQL no-atomic-safe; permitimos transaccion por op.
    atomic = True

    dependencies = [
        ('core', '0035_nominadetalle'),
    ]

    operations = [
        # 1) Imponer lock_timeout corto para esta transaccion.
        #    Si por cualquier razon hay otra transaccion bloqueando core_cfdi,
        #    el ALTER siguiente aborta limpio en 5s en vez de colgarse.
        migrations.RunSQL(
            sql="SET LOCAL lock_timeout = '5s';",
            reverse_sql="SET LOCAL lock_timeout = 0;",
        ),
        # 2) ALTER TABLE core_cfdi ADD COLUMN regimen_fiscal_receptor varchar(5) NOT NULL DEFAULT ''
        #    En PG 16 con DEFAULT constante: metadata-only, sin reescritura de filas.
        migrations.AddField(
            model_name='cfdi',
            name='regimen_fiscal_receptor',
            field=models.CharField(
                blank=True, default='',
                help_text='@RegimenFiscalReceptor (catalogo SAT c_RegimenFiscal). Bloque C.',
                max_length=5,
            ),
        ),
        # 3) CREATE TABLE core_cfdirelacionadolink + indices + constraints.
        #    Operacion sobre tabla nueva: lock irrelevante.
        migrations.CreateModel(
            name='CfdiRelacionadoLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_relacionado', models.CharField(db_index=True, help_text='UUID del CFDI relacionado (la factura ajustada por una nota, etc.)', max_length=36)),
                ('tipo_relacion', models.CharField(help_text='Catalogo SAT c_TipoRelacion (01-07+)', max_length=2)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('cfdi_origen', models.ForeignKey(db_column='cfdi_origen_uuid', help_text='CFDI que contiene el nodo <cfdi:CfdiRelacionados>', on_delete=django.db.models.deletion.CASCADE, related_name='relacionados_emitidos', to='core.cfdi')),
                ('cfdi_relacionado', models.ForeignKey(blank=True, db_column='cfdi_relacionado_uuid', help_text='CFDI relacionado si esta en BD (NULL si no lo tenemos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_recibidas', to='core.cfdi')),
            ],
            options={
                'verbose_name': 'CFDI relacionado (link)',
                'verbose_name_plural': 'CFDIs relacionados (links)',
                'indexes': [models.Index(fields=['uuid_relacionado'], name='crl_uuid_rel_idx'), models.Index(fields=['tipo_relacion'], name='crl_tipo_idx')],
                'unique_together': {('cfdi_origen', 'uuid_relacionado')},
            },
        ),
    ]
