# Generated by Django 5.2.12 on 2026-07-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cfdi_regimen_fiscal_receptor_cfdirelacionadolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdi',
            name='cancelado_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo detectamos la cancelación (no la fecha SAT de cancelación)', null=True),
        ),
        migrations.AddField(
            model_name='cfdi',
            name='estado_verificado_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Última vez que se consultó el estatus en el SAT', null=True),
        ),
        migrations.CreateModel(
            name='CompulsaSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibidos', 'Recibidos'), ('emitidos', 'Emitidos')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada al SAT'), ('lista', 'Paquete listo'), ('completada', 'Completada (diff hecho)'), ('error', 'Error'), ('sin_info', 'SAT sin información en el rango')], db_index=True, default='solicitada', max_length=20)),
                ('folio_solicitud', models.CharField(blank=True, db_index=True, max_length=40)),
                ('sat_vigentes', models.IntegerField(blank=True, null=True)),
                ('sat_cancelados', models.IntegerField(blank=True, null=True)),
                ('en_bd', models.IntegerField(blank=True, null=True)),
                ('faltantes_count', models.IntegerField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compulsas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Compulsa SAT',
                'verbose_name_plural': 'Compulsas SAT',
                'ordering': ['-creado_at'],
                'indexes': [models.Index(fields=['empresa', 'tipo', 'estado'], name='core_compul_empresa_0c8212_idx')],
            },
        ),
    ]
