# Generated by Django 5.2.12 on 2026-03-16 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(blank=True, help_text='Nombre comercial del cliente', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rfc_facturacion', models.CharField(blank=True, max_length=13)),
                ('razon_social', models.CharField(blank=True, max_length=300)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=5)),
                ('uso_cfdi', models.CharField(default='G03', max_length=10)),
                ('email_facturacion', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('basico', 'Básico'), ('pro', 'Profesional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_empresas', models.IntegerField(default=1)),
                ('max_descargas_mes', models.IntegerField(default=10)),
                ('max_conversiones_mes', models.IntegerField(default=50)),
                ('conversiones_este_mes', models.IntegerField(default=0)),
                ('descargas_este_mes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
            },
        ),
    ]
