# Generated by Django 5.2.12 on 2026-03-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailconfirmation'),
        ('core', '0009_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteprofile',
            name='max_conversiones_mes',
        ),
        migrations.RemoveField(
            model_name='clienteprofile',
            name='max_descargas_mes',
        ),
        migrations.RemoveField(
            model_name='clienteprofile',
            name='max_empresas',
        ),
        migrations.RemoveField(
            model_name='clienteprofile',
            name='plan',
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='plan_fk',
            field=models.ForeignKey(blank=True, help_text='Plan de suscripción actual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.plan'),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='plan_legacy',
            field=models.CharField(choices=[('free', 'Gratis'), ('basico', 'Básico'), ('pro', 'Profesional'), ('enterprise', 'Enterprise')], default='free', help_text='DEPRECATED — usar plan_fk', max_length=20),
        ),
    ]
