# Generated by Django 5.2.12 on 2026-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clienteprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
