# Generated by Django 5.2.12 on 2026-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clienteprofile_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='telegram_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Recibir alertas del sistema vía Telegram (solo si chat_id está vinculado)'),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID del usuario en Telegram (vinculado al bot Cirrus)', max_length=50),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
